# Generated by Django 4.2.19 on 2025-02-28 12:14

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('slug', models.CharField(default=articles.models.generate_short_uuid, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('content', models.JSONField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='著者')),
            ],
            options={
                'verbose_name_plural': '記事',
            },
        ),
    ]
