# Generated by Django 4.2.19 on 2025-02-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='test1', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
