# Generated by Django 4.2.19 on 2025-02-27 11:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=accounts.models.generate_short_uuid, max_length=16, unique=True),
        ),
    ]
