# Generated by Django 4.2.19 on 2025-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], default=1, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未着手'), (1, '進行中'), (2, '完了')], default=0, verbose_name='状態'),
        ),
    ]
