# Generated by Django 4.2.17 on 2025-02-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='id',
            field=models.CharField(default='b44c26b1-a067-4c10-a746-ac2d639d8f44', max_length=36, primary_key=True, serialize=False, verbose_name='講義コード'),
        ),
    ]
