# Generated by Django 4.2.17 on 2025-02-03 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_alter_lecture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, verbose_name='講義コード'),
        ),
    ]
