# Generated by Django 4.2.17 on 2025-02-20 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lectures', '0004_alter_lecture_description_alter_lecture_eval_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('description', models.CharField(max_length=300, verbose_name='詳細')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='締め切り')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='優先度')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lectures.lecture', verbose_name='講義')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'タスク',
            },
        ),
    ]
